# Grafana Dockerfile
FROM grafana/grafana:latest

# Add custom plugins or configurations here, if necessary
# For example, to install a plugin:
# RUN grafana-cli plugins install <plugin-name>

EXPOSE 3000

CMD ["grafana-server"]
